name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]

    steps:
    - uses: actions/checkout@v4
    - name: Configurar Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - run: npm ci

    # Inicia el servidor y espera a que esté activo
    - name: Iniciar el servidor Express
      run: |
        nohup node index.js > server.log 2>&1 &
        sleep 10 # Ajusta el tiempo si el servidor necesita más para inicializar

    # Verifica que el servidor esté funcionando
    - name: Verificar que el servidor esté disponible
      run: curl -f http://localhost:3000 || exit 1

    # Finaliza todos los procesos
    - name: Detener el servidor
      run: kill $(jobs -p)
