name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]

    steps:
    - uses: actions/checkout@v4
    - name: Configurar Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - run: npm ci

    # Inicia el servidor y lo mantiene corriendo hasta el final del workflow
    - name: Iniciar el servidor Express
      run: |
        nohup node index.js > server.log 2>&1 &
        sleep 5 # Da tiempo al servidor para inicializar

    # Verifica si el servidor responde correctamente
    - name: Verificar que el servidor esté funcionando
      run: curl -f http://localhost:3000 || exit 1

    # Detener el servidor al finalizar el workflow
    - name: Detener el servidor
      run: kill $(jobs -p)
