name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]

    steps:
    - uses: actions/checkout@v4
    - name: Configurar Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - run: npm ci

    - name: Iniciar el servidor Express
      run: |
        nohup node index.js > server.log 2>&1 &
        echo $! > server.pid

    - name: Esperar a que el servidor esté disponible
      run: npx wait-on http://localhost:3000

    - name: Verificar que el servidor esté funcionando
      run: curl -f http://localhost:3000 || exit 1

    - name: Mostrar logs del servidor
      run: cat server.log

    - name: Detener el servidor
      run: |
        if [ -f server.pid ]; then
          kill $(cat server.pid)
          rm server.pid
        fi
