name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]

    steps:
    - uses: actions/checkout@v4
    - name: Usar Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run build --if-present
    - run: npm test
    - name: Install ngrok
      run: |
        curl -s https://ngrok-agent.s3.amazonaws.com/ngrok.asc | sudo tee /etc/apt/trusted.gpg.d/ngrok.asc >/dev/null
        sudo apt update
        sudo apt install ngrok
    - name: Setup ngrok auth token
      run: |
        ngrok authtoken ${{ secrets.NGROK_AUTH_TOKEN }}
    - name: Start ngrok tunnel
      run: |
        nohup ngrok http 3000 &
        sleep 10 # Asegura que ngrok tenga tiempo para iniciar
    - name: Get ngrok URL
      run: |
        cat ngrok.log | grep -o "http://[0-9a-z.-]*.ngrok.io" | head -1
